[build]
  publish = "static"
  command = "chmod +x prebuild.sh && ./prebuild.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
