[build]
  command = "pip install -r requirements.txt && cd netlify/functions && npm install"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

[dev]
  command = "python app.py"
  port = 5000
  publish = "static"

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
